// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfbddrabvfgsbptdybda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmYmRkcmFidmZnc2JwdGR5YmRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjQ5OTIsImV4cCI6MjA2NDAwMDk5Mn0.YSuKd3WcxIAjMpQH5vao7kiZUhGwGPu4q8hQ1JDGT4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);